[package]
name = "lakeprism-media"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
native-media = ["dep:ffmpeg-next"]

[dependencies]
ffmpeg-next = { workspace = true, optional = true }
lakeprism-core = { path = "../lakeprism-core" }
thiserror.workspace = true
